[package]
name = "xaoc_utils"
version = "0.0.0"
edition = "2021"

[features]
check_label_hashes = []

[dependencies]
once_cell = "1"
ahash = "0.7"
hashbrown = "0.12"
parking_lot = "0.12"
const-fnv1a-hash = "1"
